server:
    port: 8087
    servlet:
        context-path: '/dl-authuser/' # This is the context path for the service. Used in conjunction with the API Gateway that has it mapped in the routes.

spring:
    application:
        name: dl-authuser-service
    datasource:
        url: jdbc:postgresql://localhost:5432/dl-authuser
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non_contextual_creation: true
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true

# Defining the logging level for the application
logging:
    level:
        com.xpto.distancelearning: TRACE
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: INFO


distance-learning:
    api:
        url:
#            course: 'http://localhost:8082' # I do not to hardcode the URL anymore and instead use the service name defined in the Eureka.
            course: 'http://dl-course-service/dl-course'

eureka:
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka'
    instance:
        hostname: localhost